Add functionality for views
Daniel-Kigozi/ruby-blog pull request #6
Opened 2023-07-27 14:07 UTC by Daniel-Kigozi

In the following milestone, I did the following
-Add functionality for posts views show and index 
- Add functionality for users' views index and show

2023-07-27 15:01 UTC, TadesseDev requested changes
### Hi @Daniel-Kigozi 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
 - [x] You have written a clean code ✅
 - [x]  Most of the requirement has been meet. ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 15:01 UTC, TadesseDev commented on app/views/users/index.html.erb
> +  <% end %>
- [ ] It's great you have added the `user.name` and the `user.posts_counter`, but according to the requirements, we need to render the `user.photo` alongside the other details. Please add a user profile picture here. 
- [Optional] Also, Please consider using partials here for rendering each user (`_user.html.erb` and `<%= render @users %>`). This would make your code more readable and easily maintainable.

2023-07-27 15:01 UTC, TadesseDev commented on app/views/users/show.html.erb
> +      Comments: <%= post.comments_counter %>
- [ ] Dear @Daniel-Kigozi, here we are trying to render the most recent posts of the user, hence Please make use of the `recent_posts` method you have defined inside the `User` model. 
> Something line 
``` ruby 
<% @user.recent_posts.each do |post| %>
# your code here 
<% end %>
```

2023-07-27 15:01 UTC, TadesseDev commented on app/views/posts/index.html.erb
> +        </ul>
- [ ] Here also, Please make use of the `recent_comments` to render 5 most recent comments. This will make your code more robust. 

> Something like...
```ruby 
 <% post.recent_comments.each do |comment| %>
  # Your code here
 <% end %>
```

2023-07-28 07:02 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED :1st_place_medal: 

Hi @Daniel-Kigozi , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  All required changes implemented :+1: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 08:56 UTC, merged